# Generated by Django 5.1.1 on 2024-10-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_tag_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='caption',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
